// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZiwS_Rp5uKolFdpi5lyOgZqZ0v1Fpgv8',
    appId: '1:8715905408:web:0b0638df9baaa411f03965',
    messagingSenderId: '8715905408',
    projectId: 'food-delivery-app-b29c0',
    authDomain: 'food-delivery-app-b29c0.firebaseapp.com',
    storageBucket: 'food-delivery-app-b29c0.appspot.com',
    measurementId: 'G-J4XW2P0H93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHgMR6gH5B5YJLD0A7t4DUmkx9w1ucd0s',
    appId: '1:8715905408:android:1deb3e582bc821ebf03965',
    messagingSenderId: '8715905408',
    projectId: 'food-delivery-app-b29c0',
    storageBucket: 'food-delivery-app-b29c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEbYwneh_NtAIKKbvzoQjeH8pLUxigRGI',
    appId: '1:8715905408:ios:04a70761bb17e132f03965',
    messagingSenderId: '8715905408',
    projectId: 'food-delivery-app-b29c0',
    storageBucket: 'food-delivery-app-b29c0.appspot.com',
    iosClientId: '8715905408-nt06eo6688aa228u8fnves5urpiaut04.apps.googleusercontent.com',
    iosBundleId: 'com.arif.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEbYwneh_NtAIKKbvzoQjeH8pLUxigRGI',
    appId: '1:8715905408:ios:04a70761bb17e132f03965',
    messagingSenderId: '8715905408',
    projectId: 'food-delivery-app-b29c0',
    storageBucket: 'food-delivery-app-b29c0.appspot.com',
    iosClientId: '8715905408-nt06eo6688aa228u8fnves5urpiaut04.apps.googleusercontent.com',
    iosBundleId: 'com.arif.foodDeliveryApp',
  );
}
